# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evaluate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 600)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 631, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb0 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.cb0.setFont(font)
        self.cb0.setStyleSheet("color:gray;")
        self.cb0.setObjectName("cb0")
        import sqlite3
        conn = sqlite3.connect('cricket.db')
        self.horizontalLayout.addWidget(self.cb0)
        sql="select name from teams"
        cur=conn.execute(sql)
        teams=[]
        for row in cur:
            self.cb0.addItem(row[0])        
        conn.close()
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.cb1 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.cb1.setFont(font)
        self.cb1.setStyleSheet("color:gray;")
        self.cb1.setObjectName("cb1")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.horizontalLayout.addWidget(self.cb1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(69, 180, 251, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(370, 180, 251, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.score = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(True)
        font.setWeight(75)
        self.score.setFont(font)
        self.score.setStyleSheet("color:blue;")
        self.score.setText("")
        self.score.setObjectName("score")
        self.horizontalLayout_3.addWidget(self.score)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(70, 220, 551, 301))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lw1 = QtWidgets.QListWidget(self.horizontalLayoutWidget_4)
        self.lw1.setStyleSheet("font: 10pt \"Comic Sans MS\";")
        self.lw1.setObjectName("lw1")
        self.horizontalLayout_4.addWidget(self.lw1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.lw2 = QtWidgets.QListWidget(self.horizontalLayoutWidget_4)
        self.lw2.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"color:blue;\n"
"")
        self.lw2.setObjectName("lw2")
        self.horizontalLayout_4.addWidget(self.lw2)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(270, 540, 151, 41))
        self.pushButton.setStyleSheet("font: 75 10pt \"Comic Sans MS\";\n"
"color:gray;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.calculate)

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(69, 30, 561, 23))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:gray;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        import sqlite3
        conn = sqlite3.connect('cricket.db')
        sql="select name from teams"
        teams=[]
        cur=conn.execute(sql)
        self.cb0.activated[str].connect(self.team)

    def team(self,text):
        import sqlite3
        conn = sqlite3.connect('cricket.db')
        team=self.cb0.currentText()
        match=self.cb1.currentText()
        self.lw1.clear()
        self.lw2.clear()
        self.score.clear()
        sql1 = "select players from teams where name='" + team + "'"
        cur = conn.execute(sql1)
        row = cur.fetchone()
        selected = row[0].split(',')
        self.lw1.addItems(selected)


    def calculate(self):
        import sqlite3
        conn = sqlite3.connect('cricket.db')
        teamtotal=0
        
        for i in range(self.lw1.count()-1):
            total, batscore, bowlscore, fieldscore = 0, 0, 0, 0
            nm=self.lw1.item(i).text()
            sql="select * from match where player='"+nm+"'"
            cur=conn.execute(sql)
            row=cur.fetchone()
            batscore+=int(row[1]/2)
            if row[1]>=50 and row[1]<100:batscore+=5
            if row[1]>=100:batscore+=10
            if row[1]>0:
                sr=row[1]/row[2] 
                if sr>=80 and sr<=100:batscore+=2
                if sr>100:batscore+=4
            batscore+=row[3]
            batscore+=2*row[4]
            bowlscore+=10*row[8]
            if row[8]>=3 and row[8]<5:bowlscore+=5
            if row[8]>5:bowlscore+=10
            if row[7]>0:
                eco=row[7]/(row[5]/6)
                if eco>=3.5 and eco<=4.5:bowlscore+=4
                if eco>=2 and eco<3.5:bowlscore+=7
                if eco<2:bowlscore+=10
            fieldscore=(row[9]+row[10]+row[11])*10
            total=batscore+bowlscore+fieldscore
            teamtotal+=total
            self.lw2.addItem(str(total))
        self.score.setText(str(teamtotal))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Fantasy Cricket"))
        self.label.setText(_translate("Dialog", "Select Team"))
        self.cb1.setItemText(0, _translate("Dialog", "Match 1"))
        self.cb1.setItemText(1, _translate("Dialog", "Match 2"))
        self.cb1.setItemText(2, _translate("Dialog", "Match 3"))
        self.cb1.setItemText(3, _translate("Dialog", "Match 4"))
        self.cb1.setItemText(4, _translate("Dialog", "Match 5"))
        self.label_2.setText(_translate("Dialog", "Players"))
        self.label_3.setText(_translate("Dialog", "Points"))
        self.pushButton.setText(_translate("Dialog", "Calculate Score"))
        self.label_5.setText(_translate("Dialog", "Evaluate the Performance of your Fantasy Team"))
        self.score.setText(_translate("Dialog", "--"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
